"""
35 new incident templates expanding coverage to 50+ total scenarios.
Categories: Cloud Provider, CI/CD, Data Pipeline, Networking, Security, Observability, Application.
"""

NEW_INCIDENT_TEMPLATES = [
    # ── Cloud Provider Issues (5) ─────────────────────────────────────────────
    {
        "title": "AWS Region Degradation — us-east-1",
        "description": "AWS Health Dashboard reports elevated API error rates in us-east-1. Multiple services experiencing intermittent failures including EC2, RDS, and S3.",
        "service": "aws-infrastructure",
        "severity": "SEV1",
        "root_cause": "infrastructure_failure",
        "correct_team": "infrastructure",
        "correct_remediation": "failover_db",
        "symptoms": ["EC2 API calls returning 500 errors intermittently", "RDS failover not completing — stuck in 'modifying'", "S3 PutObject requests timing out for us-east-1 buckets", "Cross-region replication lag spiking to 15 minutes"],
        "logs": ["[ERROR] aws-sdk: EC2.DescribeInstances throttled — RequestLimitExceeded", "[WARN] rds: Failover for prod-db initiated but not completing — 8 min elapsed", "[ERROR] s3: PutObject timeout after 30s for bucket prod-assets-use1", "[INFO] aws-health: us-east-1 — Elevated error rates for multiple services"],
        "metrics": {"aws_api_error_rate_pct": 25, "rds_failover_duration_min": 8, "s3_latency_p99_ms": 30000, "cross_region_lag_min": 15},
        "affected_users": 200000,
        "hints_easy": ["AWS is having a regional issue — failover to us-west-2", "Check AWS Health Dashboard for service status"],
        "hints_medium": ["Multiple AWS services affected simultaneously suggests a regional issue"],
        "hints_hard": [],
        "cascade_events": [
            {"trigger_step": 3, "condition": "not_remediated", "new_symptoms": ["Auto-scaling unable to launch new instances in us-east-1"], "metric_changes": {"aws_api_error_rate_pct": 45}, "affected_users_delta": 100000, "feedback": "🔥 CASCADE: Auto-scaling is failing — capacity shrinking!"},
        ],
    },
    {
        "title": "GCP Quota Exceeded — Compute Engine",
        "description": "Compute Engine quota for GPU instances exhausted in us-central1. ML inference pipeline unable to scale. Batch prediction jobs queuing indefinitely.",
        "service": "gcp-compute",
        "severity": "SEV3",
        "root_cause": "config_change",
        "correct_team": "infrastructure",
        "correct_remediation": "scale_horizontally",
        "symptoms": ["GPU instance launch failing with QUOTA_EXCEEDED", "ML inference latency increased 10x", "Batch prediction queue growing at 500 jobs/hour", "On-demand GPU allocation at 100% quota"],
        "logs": ["[ERROR] gce: Instance creation failed — QUOTA_EXCEEDED for NVIDIA_T4_GPUS in us-central1", "[WARN] ml-pipeline: Inference backlog 2,500 requests, avg latency 45s", "[INFO] gce: Current GPU quota usage: 96/96 (100%)"],
        "metrics": {"gpu_quota_used_pct": 100, "inference_latency_ms": 45000, "batch_queue_depth": 2500, "gpu_instances_running": 96},
        "affected_users": 500,
        "hints_easy": ["GPU quota is maxed out — request quota increase or use another region", "Scale horizontally to a region with available quota"],
        "hints_medium": ["Check quota usage across regions"],
        "hints_hard": [],
    },
    {
        "title": "Azure AD Sync Failure",
        "description": "Azure AD Connect sync failing silently. New employees unable to login. Group membership changes not propagating. Last successful sync was 18 hours ago.",
        "service": "azure-ad-connect",
        "severity": "SEV2",
        "root_cause": "config_change",
        "correct_team": "security",
        "correct_remediation": "fix_config",
        "symptoms": ["New employee accounts not provisioned for 18 hours", "Group membership changes not applying", "Azure AD Connect showing 'sync completed with errors'", "MFA enrollment failing for newly synced accounts"],
        "logs": ["[ERROR] aad-connect: Export to Azure AD failed — insufficient privileges on OU=NewHires", "[WARN] aad-connect: Delta sync completed with 342 errors", "[INFO] aad-connect: Last successful full sync: 18h ago", "[ERROR] aad-connect: Password hash sync disabled after connector account password expired"],
        "metrics": {"sync_errors": 342, "hours_since_last_sync": 18, "unprovisioned_accounts": 45, "pending_group_changes": 128},
        "affected_users": 45,
        "hints_easy": ["AD Connect sync is failing — check connector account credentials", "The connector account password expired — renew it"],
        "hints_medium": ["The sync has been failing for 18 hours — check ad connect logs"],
        "hints_hard": [],
    },
    {
        "title": "S3 Bucket Policy Misconfiguration",
        "description": "S3 bucket containing customer data had its policy changed to allow public read access. Automated scanner detected the exposure 4 hours after the change.",
        "service": "s3-data-bucket",
        "severity": "SEV1",
        "root_cause": "security_breach",
        "correct_team": "security",
        "correct_remediation": "fix_config",
        "symptoms": ["Customer PII potentially exposed for 4 hours", "S3 bucket policy allows s3:GetObject for principal '*'", "CloudTrail shows policy change by service account", "No evidence of external access yet based on access logs"],
        "logs": ["[ALERT] security-scanner: PUBLIC bucket detected — prod-customer-data-us", "[INFO] cloudtrail: PutBucketPolicy by arn:aws:iam::role/deploy-automation at 06:15:00Z", "[WARN] s3-access-log: 0 external GET requests detected during exposure window", "[ERROR] compliance: GDPR Article 33 notification may be required"],
        "metrics": {"exposure_duration_hours": 4, "external_access_count": 0, "affected_records": 850000, "compliance_risk_score": 95},
        "affected_users": 850000,
        "hints_easy": ["Fix the bucket policy immediately to remove public access", "The deploy automation role made the change — check the deployment script"],
        "hints_medium": ["Check CloudTrail for who changed the bucket policy"],
        "hints_hard": [],
    },
    {
        "title": "Lambda Cold Start Spike",
        "description": "Lambda function handling real-time notifications experiencing 10x increase in cold starts after a runtime update. P99 latency exceeding acceptable threshold.",
        "service": "lambda-notifications",
        "severity": "SEV3",
        "root_cause": "bad_deployment",
        "correct_team": "application",
        "correct_remediation": "rollback_deploy",
        "symptoms": ["Cold start rate increased from 2% to 22%", "Notification delivery latency exceeding 5s SLA", "Lambda provisioned concurrency not warming correctly", "Memory allocation unchanged but init duration doubled"],
        "logs": ["[WARN] lambda: Init duration 4200ms (was 1800ms before runtime update)", "[INFO] lambda: Runtime updated from nodejs18.x to nodejs20.x at 08:00:00Z", "[ERROR] notification-svc: 15% of push notifications exceeding 5s SLA"],
        "metrics": {"cold_start_rate_pct": 22, "init_duration_ms": 4200, "p99_latency_ms": 5200, "sla_breach_pct": 15},
        "affected_users": 12000,
        "hints_easy": ["Runtime was updated this morning — rollback to nodejs18.x", "Cold starts doubled after the runtime change"],
        "hints_medium": ["Check what changed in the Lambda configuration recently"],
        "hints_hard": [],
    },
    # ── CI/CD Pipeline (5) ────────────────────────────────────────────────────
    {
        "title": "Build Server Out of Memory",
        "description": "Jenkins build server running out of memory during concurrent builds. Jobs failing with OOM errors. Build queue growing with 45+ pending jobs.",
        "service": "jenkins-server",
        "severity": "SEV3",
        "root_cause": "memory_leak",
        "correct_team": "infrastructure",
        "correct_remediation": "restart_service",
        "symptoms": ["Jenkins master JVM heap at 95%", "Concurrent builds reduced from 8 to 2", "45 builds queued, average wait time 90 minutes", "Jenkins workspace not cleaned up — 200GB accumulated"],
        "logs": ["[ERROR] jenkins: java.lang.OutOfMemoryError: Java heap space", "[WARN] jenkins: GC overhead limit exceeded, 98% time in GC", "[INFO] jenkins: Workspace disk usage: 200GB across 1,200 old builds"],
        "metrics": {"jvm_heap_pct": 95, "builds_queued": 45, "avg_wait_time_min": 90, "workspace_size_gb": 200},
        "affected_users": 80,
        "hints_easy": ["Jenkins is OOM — restart and clean old workspaces", "200GB of old build artifacts need cleanup"],
        "hints_medium": ["JVM heap at 95% with heavy GC — memory exhaustion"],
        "hints_hard": [],
    },
    {
        "title": "Container Registry Disk Full",
        "description": "Docker container registry running out of storage. New image pushes failing. CI/CD pipelines blocked on image publish step.",
        "service": "container-registry",
        "severity": "SEV2",
        "root_cause": "infrastructure_failure",
        "correct_team": "infrastructure",
        "correct_remediation": "fix_config",
        "symptoms": ["Image push returning 'insufficient storage'", "Registry disk at 98% — 1.8TB of 2TB used", "No image retention policy configured", "15 CI/CD pipelines blocked on push step"],
        "logs": ["[ERROR] registry: blob upload failed — insufficient storage", "[WARN] registry: disk usage 1.8TB/2TB (98%)", "[INFO] registry: 45,000 image tags, oldest from 2 years ago"],
        "metrics": {"disk_usage_pct": 98, "total_images": 45000, "pipelines_blocked": 15, "disk_size_tb": 2},
        "affected_users": 50,
        "hints_easy": ["Set up image retention policy to clean old images", "Fix the config to add garbage collection"],
        "hints_medium": ["No retention policy — images accumulating for 2 years"],
        "hints_hard": [],
    },
    {
        "title": "Flaky Test Blocking Production Deploy",
        "description": "Integration test suite has 3 flaky tests failing intermittently. Deploy pipeline requires 100% pass rate. 12 production hotfixes queued behind the flaky gate.",
        "service": "ci-pipeline",
        "severity": "SEV2",
        "root_cause": "bad_deployment",
        "correct_team": "application",
        "correct_remediation": "fix_config",
        "symptoms": ["3 tests failing 40% of the time due to race conditions", "Deploy pipeline blocked for 6 hours", "12 hotfixes including a security patch waiting", "Test retry budget exhausted after 5 attempts"],
        "logs": ["[ERROR] test-runner: test_checkout_flow FAILED — timeout waiting for async event", "[WARN] ci: Deploy gate blocked — pass rate 97% (required: 100%)", "[INFO] ci: 12 commits queued for production deploy, oldest 6h ago"],
        "metrics": {"test_pass_rate_pct": 97, "queued_deploys": 12, "hours_blocked": 6, "flaky_test_count": 3},
        "affected_users": 50,
        "hints_easy": ["Skip or quarantine the flaky tests to unblock deploys", "Fix the pipeline config to allow known-flaky test exclusion"],
        "hints_medium": ["Tests failing intermittently — likely race conditions"],
        "hints_hard": [],
    },
    {
        "title": "Secret Rotation Breaking Deployment",
        "description": "Automated secret rotation updated database credentials but didn't restart dependent services. New deployments using old secrets failing to connect.",
        "service": "vault-secrets",
        "severity": "SEV2",
        "root_cause": "config_change",
        "correct_team": "platform",
        "correct_remediation": "restart_service",
        "symptoms": ["New pod deployments failing with 'authentication failed'", "Vault rotated DB password 2 hours ago", "Running pods still work (using old cached credentials)", "New pods pulling fresh (rotated) credentials that DB hasn't applied yet"],
        "logs": ["[ERROR] app-deploy-new: FATAL: password authentication failed for user 'app_svc'", "[INFO] vault: Secret database/creds/app-role rotated at 14:00:00Z", "[WARN] pg: max_connections nearly reached — old and new credential sessions competing"],
        "metrics": {"deploy_failure_rate_pct": 100, "running_pods_healthy": 8, "new_pods_failing": 4, "hours_since_rotation": 2},
        "affected_users": 0,
        "hints_easy": ["Restart services to pick up the new credentials", "Vault rotated secrets but services weren't restarted"],
        "hints_medium": ["New pods fail but old pods work — credential mismatch"],
        "hints_hard": [],
    },
    {
        "title": "Container Image Critical Vulnerability",
        "description": "Container security scan detected CVE-2024-9999 (CVSS 9.8) in the base image used by 23 production services. Exploit code is publicly available.",
        "service": "container-security",
        "severity": "SEV1",
        "root_cause": "security_breach",
        "correct_team": "security",
        "correct_remediation": "rollback_deploy",
        "symptoms": ["Critical CVE detected in python:3.11-slim base image", "23 production services affected", "Public exploit available — actively exploited in the wild", "Compliance requires patching within 24 hours"],
        "logs": ["[ALERT] trivy: CVE-2024-9999 (CRITICAL, CVSS 9.8) in python:3.11-slim", "[INFO] trivy: 23 deployments using affected base image", "[WARN] security: Public exploit code detected on GitHub", "[INFO] compliance: 24h remediation window per SOC2 policy"],
        "metrics": {"cvss_score": 9.8, "affected_services": 23, "hours_to_comply": 24, "exploit_available": True},
        "affected_users": 0,
        "hints_easy": ["Rebuild all images with patched base image immediately", "Rollback to a known-safe base image version"],
        "hints_medium": ["CVE is publicly exploitable — urgent patching required"],
        "hints_hard": [],
    },
    # ── Data Pipeline (5) ─────────────────────────────────────────────────────
    {
        "title": "Kafka Topic Retention Overflow",
        "description": "High-volume Kafka topic hit disk quota. Old messages being deleted before consumers processed them. 3 consumer groups lost data.",
        "service": "kafka-cluster",
        "severity": "SEV2",
        "root_cause": "config_change",
        "correct_team": "platform",
        "correct_remediation": "fix_config",
        "symptoms": ["Consumer groups reporting 'offset out of range'", "Topic disk usage exceeded retention quota", "3 consumer groups lost approximately 2 hours of data", "Producers still writing — old data being purged aggressively"],
        "logs": ["[ERROR] kafka: Log segment deleted before consumer group 'analytics' read offset 45000000", "[WARN] kafka: Topic 'user-events' disk usage 500GB exceeds quota 400GB", "[ERROR] consumer-analytics: OffsetOutOfRangeException — resetting to latest"],
        "metrics": {"topic_disk_gb": 500, "disk_quota_gb": 400, "consumer_groups_affected": 3, "data_loss_hours": 2},
        "affected_users": 0,
        "hints_easy": ["Increase disk quota or adjust retention policy", "Fix the topic configuration for proper retention"],
        "hints_medium": ["Consumers falling behind while disk purges old data"],
        "hints_hard": [],
    },
    {
        "title": "Spark Job OOM on Large Dataset",
        "description": "Daily Spark ETL job failing with out-of-memory on executor nodes. Dataset grew 5x after a partner integration went live. Previous resource allocation insufficient.",
        "service": "spark-cluster",
        "severity": "SEV3",
        "root_cause": "infrastructure_failure",
        "correct_team": "application",
        "correct_remediation": "scale_horizontally",
        "symptoms": ["Spark executors OOM-killed during shuffle phase", "Dataset size grew from 200GB to 1TB after partner integration", "Job has failed 3 consecutive nights", "Downstream reports 3 days stale"],
        "logs": ["[ERROR] spark-exec-05: Container killed by YARN for exceeding memory limits. 16GB used of 16GB limit", "[WARN] spark: Shuffle spill to disk exceeding 500GB", "[INFO] data-pipeline: Input dataset size: 1.02TB (was 200GB last week)"],
        "metrics": {"dataset_size_gb": 1020, "executor_memory_gb": 16, "consecutive_failures": 3, "report_staleness_days": 3},
        "affected_users": 200,
        "hints_easy": ["Scale executor memory or add more executors for the larger dataset", "Dataset grew 5x — need more compute resources"],
        "hints_medium": ["OOM on shuffle — dataset size exceeds executor capacity"],
        "hints_hard": [],
    },
    {
        "title": "Data Lake Schema Drift",
        "description": "Upstream API changed response schema without notice. ETL pipeline ingesting null values for 8 renamed fields. Downstream ML models producing garbage predictions.",
        "service": "data-lake",
        "severity": "SEV2",
        "root_cause": "config_change",
        "correct_team": "application",
        "correct_remediation": "fix_config",
        "symptoms": ["8 columns returning NULL since yesterday's API update", "ML model accuracy dropped from 94% to 12%", "Schema validation disabled in production pipeline", "Partner API changelog shows 'breaking changes' released yesterday"],
        "logs": ["[WARN] etl: Column 'user_segment' not found in API response — defaulting to NULL", "[ERROR] ml-pipeline: Model accuracy degraded to 12% — input features contain 60% nulls", "[INFO] partner-api: v3.2 released with renamed fields (see changelog)"],
        "metrics": {"null_rate_pct": 60, "model_accuracy_pct": 12, "affected_columns": 8, "hours_since_schema_change": 28},
        "affected_users": 5000,
        "hints_easy": ["Update ETL schema mapping to match new API v3.2 fields", "Fix the config to map renamed fields correctly"],
        "hints_medium": ["Columns returning NULL after upstream API change"],
        "hints_hard": [],
    },
    {
        "title": "Streaming Backpressure Cascade",
        "description": "Flink streaming job experiencing backpressure. Source read rate throttled to 10% capacity. Watermark delay growing, causing late event data to be dropped.",
        "service": "flink-streaming",
        "severity": "SEV3",
        "root_cause": "memory_leak",
        "correct_team": "application",
        "correct_remediation": "restart_service",
        "symptoms": ["Backpressure at 95% on window operator", "Source throughput throttled from 50k to 5k events/s", "Watermark delay exceeding 10 minutes", "Late events being dropped — data completeness degrading"],
        "logs": ["[WARN] flink: Backpressure detected on WindowOperator — ratio 0.95", "[WARN] flink: TaskManager heap usage 90% — GC frequency increasing", "[ERROR] flink: Watermark delay 10m32s — late events dropped: 45,000"],
        "metrics": {"backpressure_ratio": 0.95, "throughput_events_per_sec": 5000, "watermark_delay_min": 10.5, "events_dropped": 45000},
        "affected_users": 0,
        "hints_easy": ["Restart the Flink job to clear accumulated state", "Memory leak causing backpressure — restart will fix temporarily"],
        "hints_medium": ["Backpressure with growing heap usage suggests state accumulation"],
        "hints_hard": [],
    },
    {
        "title": "ETL Data Quality Violation",
        "description": "Data quality checks catching 15% anomaly rate in customer address data. Root cause: geocoding API returning cached stale results for 3 days.",
        "service": "data-quality",
        "severity": "SEV3",
        "root_cause": "dependency_outage",
        "correct_team": "application",
        "correct_remediation": "flush_cache",
        "symptoms": ["Address validation failing for 15% of records", "Geocoding API returning coordinates from 3 days ago", "Shipping cost calculations incorrect for affected orders", "Data quality alert: anomaly score 0.87 (threshold: 0.5)"],
        "logs": ["[WARN] dq-check: Address anomaly rate 15.2% (threshold 5%)", "[ERROR] geocoding: Cache hit ratio 100% — no fresh API calls in 72 hours", "[INFO] geocoding: Cache TTL set to 720h (should be 24h) — config error"],
        "metrics": {"anomaly_rate_pct": 15.2, "cache_hit_ratio_pct": 100, "cache_ttl_hours": 720, "affected_orders": 3400},
        "affected_users": 3400,
        "hints_easy": ["Flush the geocoding cache — TTL is set too high (720h vs 24h)", "Fix the cache TTL config and flush stale entries"],
        "hints_medium": ["100% cache hit ratio for 72 hours is abnormal"],
        "hints_hard": [],
    },
    # ── Networking (5) ────────────────────────────────────────────────────────
    {
        "title": "VPN Tunnel Flapping",
        "description": "Site-to-site VPN tunnel between primary and DR datacenter flapping every 2-3 minutes. Database replication and backup jobs failing intermittently.",
        "service": "vpn-gateway",
        "severity": "SEV2",
        "root_cause": "infrastructure_failure",
        "correct_team": "networking",
        "correct_remediation": "fix_config",
        "symptoms": ["VPN tunnel up/down cycling every 2-3 minutes", "DB replication to DR site failing 40% of the time", "Backup jobs timing out during tunnel drops", "IPSec rekeying happening too frequently"],
        "logs": ["[WARN] vpn-gw: IKE SA expired — rekeying initiated", "[ERROR] vpn-gw: Phase 2 SA negotiation failed — DPD timeout", "[WARN] vpn-gw: Tunnel DOWN — peer not responding to keepalives", "[INFO] vpn-gw: Tunnel UP — re-established after 15s"],
        "metrics": {"tunnel_flap_count_1h": 25, "replication_failure_pct": 40, "backup_failures_24h": 8, "avg_downtime_per_flap_sec": 15},
        "affected_users": 0,
        "hints_easy": ["DPD timeout too aggressive — increase keepalive interval", "Fix the VPN config: increase DPD timeout and SA lifetime"],
        "hints_medium": ["Tunnel flapping on 2-3 min cycle — check rekeying settings"],
        "hints_hard": [],
    },
    {
        "title": "Load Balancer Health Check Misconfigured",
        "description": "ALB health check path changed to a non-existent endpoint. All targets marked unhealthy. 503 errors for all traffic despite backend pods being healthy.",
        "service": "alb-production",
        "severity": "SEV1",
        "root_cause": "config_change",
        "correct_team": "infrastructure",
        "correct_remediation": "fix_config",
        "symptoms": ["All ALB target group targets showing 'unhealthy'", "100% of requests returning 503 Service Unavailable", "Backend pods responding normally on direct access", "Health check path changed from /health to /healthz (non-existent)"],
        "logs": ["[ERROR] alb: All targets in tg-prod unhealthy — health check returns 404", "[INFO] alb: Health check config updated at 16:30:00Z — path changed to /healthz", "[WARN] alb: 0 healthy targets — returning 503 to all clients"],
        "metrics": {"healthy_targets": 0, "total_targets": 8, "error_rate_pct": 100, "http_503_count_per_min": 5000},
        "affected_users": 150000,
        "hints_easy": ["Health check path is wrong — change /healthz back to /health", "Fix the ALB health check config"],
        "hints_medium": ["All targets unhealthy but pods are fine — health check issue"],
        "hints_hard": [],
    },
    {
        "title": "mTLS Certificate Chain Invalid",
        "description": "Mutual TLS authentication between microservices failing after intermediate CA certificate expired. Services cannot establish trusted connections.",
        "service": "mtls-mesh",
        "severity": "SEV1",
        "root_cause": "certificate_expiry",
        "correct_team": "security",
        "correct_remediation": "rotate_credentials",
        "symptoms": ["Inter-service mTLS handshakes failing with 'certificate verify failed'", "Intermediate CA certificate expired 6 hours ago", "All service-to-service calls returning connection reset", "Service mesh reporting 0% mTLS success rate"],
        "logs": ["[ERROR] envoy: TLS handshake failed: SSL_ERROR_CERTIFICATE_VERIFY_FAILED", "[ERROR] envoy: Intermediate CA 'Internal Services CA' expired at 2024-01-15T00:00:00Z", "[WARN] cert-manager: Renewal attempt failed — ACME challenge not responding"],
        "metrics": {"mtls_success_rate_pct": 0, "cert_expiry_hours_ago": 6, "affected_services": 45, "error_rate_pct": 100},
        "affected_users": 200000,
        "hints_easy": ["Intermediate CA certificate expired — issue new cert chain", "Rotate the certificate chain to restore mTLS"],
        "hints_medium": ["All service-to-service TLS failing — check cert chain validity"],
        "hints_hard": [],
    },
    {
        "title": "BGP Route Leak",
        "description": "BGP misconfiguration advertising internal prefixes to upstream transit provider. Some external traffic being routed through DR path, adding 150ms latency.",
        "service": "bgp-routing",
        "severity": "SEV2",
        "root_cause": "config_change",
        "correct_team": "networking",
        "correct_remediation": "fix_config",
        "symptoms": ["Internal /16 prefix visible in public routing tables", "30% of traffic taking suboptimal DR path", "Latency increased 150ms for affected traffic", "BGP route filter updated 3 hours ago by automation"],
        "logs": ["[ALERT] bgp-monitor: Internal prefix 10.0.0.0/16 detected in RIPE RIS", "[WARN] bgp: Route filter update at 11:00:00Z removed prefix deny rule", "[INFO] bgp: AS path for 10.0.0.0/16: AS12345 AS67890 (leaked to transit)"],
        "metrics": {"traffic_on_suboptimal_path_pct": 30, "added_latency_ms": 150, "hours_since_leak": 3, "affected_prefixes": 1},
        "affected_users": 50000,
        "hints_easy": ["Fix the BGP route filter to stop advertising internal prefixes", "A route filter change leaked the internal prefix"],
        "hints_medium": ["Internal prefix visible externally — check BGP route filters"],
        "hints_hard": [],
    },
    {
        "title": "Service Mesh Sidecar CPU Throttling",
        "description": "Envoy sidecar proxies hitting CPU limits across the mesh. Request latency increasing as sidecars are throttled. Root cause: debug logging accidentally enabled mesh-wide.",
        "service": "istio-mesh",
        "severity": "SEV2",
        "root_cause": "config_change",
        "correct_team": "platform",
        "correct_remediation": "fix_config",
        "symptoms": ["Envoy sidecar CPU at 100% across all pods", "P99 latency increased 5x mesh-wide", "Sidecar access logs growing at 10GB/hour", "Debug-level logging enabled in mesh config"],
        "logs": ["[WARN] istio: Sidecar CPU throttled on 85% of pods", "[INFO] istio: MeshConfig updated at 09:00:00Z — accessLogLevel: DEBUG", "[ERROR] envoy: Log buffer overflow — dropping access log entries"],
        "metrics": {"sidecar_cpu_throttle_pct": 85, "p99_latency_multiplier": 5, "log_volume_gb_per_hour": 10, "mesh_pods_affected": 340},
        "affected_users": 30000,
        "hints_easy": ["Debug logging was enabled mesh-wide — set back to WARN", "Fix the MeshConfig to disable debug logging"],
        "hints_medium": ["All sidecars at 100% CPU — check what's generating the load"],
        "hints_hard": [],
    },
    # ── Security (5) ──────────────────────────────────────────────────────────
    {
        "title": "API Key Leaked in Public Repository",
        "description": "Production API key with admin privileges committed to a public GitHub repository. Secret scanning alert triggered. Key has been live for 48 hours.",
        "service": "api-key-management",
        "severity": "SEV1",
        "root_cause": "security_breach",
        "correct_team": "security",
        "correct_remediation": "rotate_credentials",
        "symptoms": ["Production admin API key found in public GitHub repo", "Key has been exposed for 48 hours", "No evidence of unauthorized usage yet", "Key has full admin access to production database"],
        "logs": ["[ALERT] github: Secret scanning detected API key in repo 'dev-playground'", "[INFO] audit: API key last used by IP 10.0.1.5 (internal) — no external usage detected", "[WARN] iam: Key has AdminFull permission set — critical exposure"],
        "metrics": {"exposure_duration_hours": 48, "external_usage_count": 0, "permission_level": "admin", "affected_resources": 15},
        "affected_users": 0,
        "hints_easy": ["Immediately rotate the exposed API key", "Rotate credential and audit for any unauthorized usage"],
        "hints_medium": ["48-hour exposure window — need to check audit logs"],
        "hints_hard": [],
    },
    {
        "title": "DDoS Volumetric Attack",
        "description": "Massive UDP flood targeting primary DNS infrastructure. 45Gbps of attack traffic overwhelming DDoS mitigation capacity. Legitimate DNS resolution degraded.",
        "service": "dns-infrastructure",
        "severity": "SEV1",
        "root_cause": "traffic_spike",
        "correct_team": "networking",
        "correct_remediation": "block_traffic",
        "symptoms": ["45Gbps UDP flood targeting DNS servers", "DDoS mitigation at 90% capacity", "DNS query response time increased from 5ms to 2000ms", "Legitimate query drop rate at 25%"],
        "logs": ["[ALERT] ddos-mitigation: Volumetric attack detected — 45Gbps UDP flood", "[WARN] dns: Query response time 2000ms (SLA: 50ms)", "[ERROR] ddos-mitigation: Scrubbing capacity 90% — may need upstream activation"],
        "metrics": {"attack_volume_gbps": 45, "mitigation_capacity_pct": 90, "query_latency_ms": 2000, "legitimate_drop_rate_pct": 25},
        "affected_users": 500000,
        "hints_easy": ["Activate upstream DDoS mitigation and block attack traffic patterns", "Block the flood traffic at the network edge"],
        "hints_medium": ["45Gbps UDP flood — need upstream scrubbing activation"],
        "hints_hard": [],
    },
    {
        "title": "Privilege Escalation Attempt Detected",
        "description": "SIEM detected a service account attempting to access resources outside its scope. Account may have been compromised through a supply chain attack on a dependency.",
        "service": "iam-security",
        "severity": "SEV1",
        "root_cause": "security_breach",
        "correct_team": "security",
        "correct_remediation": "block_traffic",
        "symptoms": ["Service account 'ci-deploy' accessing prod secrets it shouldn't", "Access pattern doesn't match normal CI/CD behavior", "npm dependency 'event-logger' updated with suspicious code", "Outbound connection attempts to external C2 server"],
        "logs": ["[ALERT] siem: Privilege escalation — ci-deploy accessing vault/secrets/prod/*", "[WARN] npm-audit: event-logger@2.1.4 contains obfuscated code in postinstall", "[ERROR] firewall: Blocked outbound connection to 185.143.223.x:4443 from ci-runner-03"],
        "metrics": {"unauthorized_access_attempts": 34, "suspicious_outbound_connections": 8, "compromised_dependency_installs": 12, "hours_since_first_detection": 2},
        "affected_users": 0,
        "hints_easy": ["Block the compromised service account immediately", "Supply chain attack via npm dependency — isolate affected systems"],
        "hints_medium": ["Service account behavior changed after dependency update"],
        "hints_hard": [],
    },
    {
        "title": "Data Exfiltration Alert",
        "description": "DLP system detected unusual data export pattern. An internal user downloaded 500MB of customer data via API in 30 minutes — 100x their normal usage.",
        "service": "dlp-monitoring",
        "severity": "SEV1",
        "root_cause": "security_breach",
        "correct_team": "security",
        "correct_remediation": "block_traffic",
        "symptoms": ["500MB data export by single user in 30 minutes", "Normal usage for this user: 5MB/day", "Data includes customer PII and financial records", "User account logged in from unusual location (different country)"],
        "logs": ["[ALERT] dlp: Anomalous data export — user 'analyst@corp' exported 500MB in 30min", "[WARN] auth: user 'analyst@corp' login from 185.*.*.* (unusual location: Romania)", "[INFO] api-audit: 2,340 API calls to /api/v2/customers/export in 30 minutes"],
        "metrics": {"data_exported_mb": 500, "normal_daily_mb": 5, "api_calls_in_window": 2340, "unusual_location": True},
        "affected_users": 150000,
        "hints_easy": ["Block the user account immediately and investigate", "Login from unusual location + massive data export = likely compromised account"],
        "hints_medium": ["100x normal data export volume from unusual location"],
        "hints_hard": [],
    },
    {
        "title": "WAF False Positive Blocking Legitimate Traffic",
        "description": "WAF rule update blocking 20% of legitimate API requests. Rule matching on common JSON payload patterns. Revenue-impacting for e-commerce checkout flow.",
        "service": "waf-gateway",
        "severity": "SEV2",
        "root_cause": "config_change",
        "correct_team": "security",
        "correct_remediation": "fix_config",
        "symptoms": ["20% of legitimate POST requests blocked by WAF", "Checkout completion rate dropped from 85% to 65%", "WAF rule 942100 matching on JSON array patterns", "New rule deployed 4 hours ago for SQL injection protection"],
        "logs": ["[WARN] waf: Rule 942100 blocking request — pattern match: '[' in body", "[ERROR] checkout: Conversion rate dropped 20% — WAF blocking checkout payloads", "[INFO] waf: Rule 942100 deployed at 10:00:00Z as part of security hardening"],
        "metrics": {"false_positive_rate_pct": 20, "checkout_conversion_drop_pct": 20, "blocked_requests_per_min": 800, "revenue_impact_pct": 15},
        "affected_users": 25000,
        "hints_easy": ["Tune WAF rule 942100 to exclude checkout endpoint", "Fix the WAF config to whitelist JSON array patterns for checkout"],
        "hints_medium": ["New WAF rule matching legitimate JSON — false positives"],
        "hints_hard": [],
    },
    # ── Observability (5) ─────────────────────────────────────────────────────
    {
        "title": "Prometheus Server OOM — Monitoring Blackout",
        "description": "Prometheus server crashed due to OOM. No metrics collection for 45 minutes. Alerting system blind. Discovered only because a developer noticed missing graphs.",
        "service": "prometheus-server",
        "severity": "SEV2",
        "root_cause": "memory_leak",
        "correct_team": "infrastructure",
        "correct_remediation": "restart_service",
        "symptoms": ["No metrics data for 45 minutes", "All Grafana dashboards showing 'No data'", "Alertmanager has no alerts (because Prometheus is down)", "PagerDuty didn't fire because alert source is dead"],
        "logs": ["[FATAL] prometheus: OOM killed — RSS 32GB exceeded cgroup limit", "[WARN] prometheus: TSDB head series count: 2.1M (was 800K last month)", "[INFO] prometheus: Compaction backlog growing — 45 blocks pending"],
        "metrics": {"collection_gap_minutes": 45, "head_series_count": 2100000, "memory_limit_gb": 32, "tsdb_blocks_pending": 45},
        "affected_users": 0,
        "hints_easy": ["Restart Prometheus and investigate the series cardinality growth", "Memory leak from cardinality explosion — restart and add limits"],
        "hints_medium": ["Series count tripled — high cardinality labels causing OOM"],
        "hints_hard": [],
    },
    {
        "title": "Log Pipeline Saturation",
        "description": "Centralized logging pipeline (Fluentd → Elasticsearch) saturated. Log ingestion dropping 40% of messages. Debug logs from a chatty service consuming 80% of bandwidth.",
        "service": "logging-pipeline",
        "severity": "SEV3",
        "root_cause": "config_change",
        "correct_team": "platform",
        "correct_remediation": "fix_config",
        "symptoms": ["40% of log messages being dropped", "Elasticsearch ingestion queue at 100%", "Single service generating 80% of log volume", "Debug logging enabled on recommendation-engine after config change"],
        "logs": ["[WARN] fluentd: Buffer overflow — dropping 40% of incoming messages", "[INFO] fluentd: Top source: recommendation-engine at 50GB/hour", "[ERROR] elasticsearch: Bulk indexing rejected — thread pool queue full"],
        "metrics": {"log_drop_rate_pct": 40, "top_source_gb_per_hour": 50, "es_queue_pct": 100, "total_log_volume_gb_per_hour": 62},
        "affected_users": 0,
        "hints_easy": ["Set recommendation-engine logging back to INFO level", "Fix the config to reduce debug log verbosity"],
        "hints_medium": ["One service producing 80% of log volume — check its log level"],
        "hints_hard": [],
    },
    {
        "title": "Alert Fatigue — 1000+ Firing Alerts",
        "description": "Alertmanager showing 1,247 firing alerts. On-call engineer overwhelmed and ignoring all pages. Root cause: noisy alert threshold set too low after a 'shift left' initiative.",
        "service": "alertmanager",
        "severity": "SEV3",
        "root_cause": "config_change",
        "correct_team": "platform",
        "correct_remediation": "fix_config",
        "symptoms": ["1,247 alerts currently firing", "On-call response rate dropped to 5%", "Real incidents buried in noise", "Alert thresholds lowered 10x two weeks ago"],
        "logs": ["[WARN] alertmanager: 1,247 active alerts — potential fatigue risk", "[INFO] alertmanager: Alert thresholds updated 2 weeks ago — global 10x reduction", "[ERROR] pagerduty: On-call engineer acknowledged 3/60 pages in last shift"],
        "metrics": {"active_alerts": 1247, "oncall_response_rate_pct": 5, "true_positive_rate_pct": 8, "threshold_reduction_factor": 10},
        "affected_users": 0,
        "hints_easy": ["Revert alert thresholds to previous values", "Fix the config to restore reasonable alert thresholds"],
        "hints_medium": ["Alert threshold was reduced 10x — causing noise flood"],
        "hints_hard": [],
    },
    {
        "title": "Distributed Tracing Backend OOM",
        "description": "Jaeger collector running out of memory. Trace data being dropped for 30% of requests. Root cause: unbounded span storage from recursive API calls.",
        "service": "jaeger-collector",
        "severity": "SEV3",
        "root_cause": "memory_leak",
        "correct_team": "infrastructure",
        "correct_remediation": "restart_service",
        "symptoms": ["30% of traces incomplete — spans missing", "Jaeger collector heap at 94%", "Recursive API loop generating 10,000+ spans per trace", "Trace storage backend query timeouts"],
        "logs": ["[WARN] jaeger: Collector heap 94% — span buffer overflow imminent", "[ERROR] jaeger: Trace abc123 has 12,456 spans — possible infinite loop", "[WARN] jaeger: Dropping 30% of incoming spans due to memory pressure"],
        "metrics": {"span_drop_rate_pct": 30, "collector_heap_pct": 94, "max_spans_per_trace": 12456, "traces_per_sec": 5000},
        "affected_users": 0,
        "hints_easy": ["Restart collector and add max-spans-per-trace limit", "Memory leak from a recursive API generating unlimited spans"],
        "hints_medium": ["One trace has 12k+ spans — a recursive loop is causing the bloat"],
        "hints_hard": [],
    },
    {
        "title": "Metrics Cardinality Explosion",
        "description": "Custom metric with user_id label causing Prometheus cardinality to explode. 5 million active time series consuming all available memory. Query performance degraded.",
        "service": "metrics-infrastructure",
        "severity": "SEV3",
        "root_cause": "config_change",
        "correct_team": "application",
        "correct_remediation": "fix_config",
        "symptoms": ["5 million active time series (was 500K)", "Prometheus query response time increased from 200ms to 30s", "Memory usage 95% on Prometheus instances", "A new metric 'http_request_duration_by_user' deployed yesterday"],
        "logs": ["[WARN] prometheus: Total active series: 5,012,345", "[INFO] prom-audit: New metric 'http_request_duration_by_user' label cardinality: 4.2M unique user_ids", "[WARN] prometheus: Query exceeded 30s timeout — PromQL engine overloaded"],
        "metrics": {"total_active_series": 5012345, "series_last_month": 500000, "query_p99_ms": 30000, "memory_pct": 95},
        "affected_users": 0,
        "hints_easy": ["Remove the user_id label from the metric — use histograms instead", "Fix the metric config to drop the high-cardinality user_id label"],
        "hints_medium": ["10x cardinality increase correlates with new metric deployment"],
        "hints_hard": [],
    },
    # ── Application Issues (5) ────────────────────────────────────────────────
    {
        "title": "Race Condition in Checkout Flow",
        "description": "Double-charge bug in checkout. Under high concurrency, payment confirmation webhook and polling check both trigger fulfillment. 0.5% of orders charged twice.",
        "service": "checkout-service",
        "severity": "SEV2",
        "root_cause": "bad_deployment",
        "correct_team": "application",
        "correct_remediation": "rollback_deploy",
        "symptoms": ["0.5% of orders charged twice", "Duplicate fulfillment events for same order", "Issue only occurs under high concurrency", "New checkout code deployed 3 days ago removed idempotency lock"],
        "logs": ["[ERROR] checkout: Order #78945 fulfilled twice — duplicate payment confirmation", "[WARN] checkout: Race between webhook handler and polling check — both triggered fulfillment", "[INFO] deploy-log: checkout-service v2.8.0 deployed 3 days ago — refactored payment confirmation flow"],
        "metrics": {"double_charge_rate_pct": 0.5, "affected_orders": 156, "total_refund_amount_usd": 23400, "concurrent_requests_peak": 450},
        "affected_users": 156,
        "hints_easy": ["Rollback to v2.7.x which had the idempotency lock", "New deployment removed idempotency protection"],
        "hints_medium": ["Double charges only under high concurrency — race condition"],
        "hints_hard": [],
    },
    {
        "title": "Infinite Redirect Loop",
        "description": "OAuth callback redirecting in an infinite loop between auth server and application. Browser hitting redirect limit. Only affects users with specific cookie state.",
        "service": "oauth-integration",
        "severity": "SEV2",
        "root_cause": "config_change",
        "correct_team": "application",
        "correct_remediation": "fix_config",
        "symptoms": ["ERR_TOO_MANY_REDIRECTS for 30% of login attempts", "Redirect loop between /auth/callback and /auth/login", "Only users with existing expired session cookies affected", "OAuth redirect_uri config mismatch after domain migration"],
        "logs": ["[ERROR] oauth: Redirect loop detected — /auth/callback → /auth/login → /auth/callback (5 cycles)", "[WARN] oauth: redirect_uri mismatch — expected app.example.com, got old.example.com", "[INFO] infra: Domain migration from old.example.com to app.example.com completed last week"],
        "metrics": {"redirect_loop_rate_pct": 30, "affected_sessions": 8500, "avg_redirects_before_error": 10, "error_rate_pct": 30},
        "affected_users": 8500,
        "hints_easy": ["Update OAuth redirect_uri to the new domain", "Fix the config for the correct redirect_uri after domain migration"],
        "hints_medium": ["Redirect loop correlates with domain migration — check OAuth config"],
        "hints_hard": [],
    },
    {
        "title": "GraphQL N+1 Query Performance Degradation",
        "description": "GraphQL API response time degraded 20x after adding a new resolver. Each user query triggering N+1 database queries. Database connection pool near exhaustion.",
        "service": "graphql-api",
        "severity": "SEV3",
        "root_cause": "bad_deployment",
        "correct_team": "application",
        "correct_remediation": "rollback_deploy",
        "symptoms": ["API response time increased from 100ms to 2s", "Database queries per request increased from 3 to 150+", "Connection pool usage at 90%", "New 'userPreferences' resolver added yesterday without DataLoader"],
        "logs": ["[WARN] graphql: Query 'getUser' executing 156 SQL queries (was 3)", "[ERROR] pg: Connection pool nearly exhausted — 450/500 connections in use", "[INFO] deploy: graphql-api v3.2.1 deployed — added userPreferences resolver"],
        "metrics": {"api_response_time_ms": 2000, "queries_per_request": 156, "db_connection_pool_pct": 90, "requests_per_sec": 1200},
        "affected_users": 5000,
        "hints_easy": ["Rollback to v3.2.0 which didn't have the N+1 resolver", "New resolver causing 150+ queries per request"],
        "hints_medium": ["Query count per request exploded after new resolver deploy"],
        "hints_hard": [],
    },
    {
        "title": "Feature Flag Misconfiguration",
        "description": "Feature flag 'enable-new-pricing' accidentally enabled for 100% of users in production. New pricing model not ready — showing $0.00 for all products.",
        "service": "feature-flags",
        "severity": "SEV1",
        "root_cause": "config_change",
        "correct_team": "application",
        "correct_remediation": "fix_config",
        "symptoms": ["All product prices showing $0.00", "Feature flag 'enable-new-pricing' at 100% rollout", "Flag was meant for 5% canary — but set to 100% by mistake", "Orders being placed at $0.00 — revenue loss accelerating"],
        "logs": ["[ALERT] pricing: All product prices returning $0.00", "[INFO] launchdarkly: Flag 'enable-new-pricing' updated to 100% by user admin@corp", "[ERROR] order-svc: Order #89012 placed for $0.00 — pricing data missing"],
        "metrics": {"zero_price_rate_pct": 100, "revenue_loss_per_hour_usd": 450000, "orders_at_zero": 340, "flag_rollout_pct": 100},
        "affected_users": 100000,
        "hints_easy": ["Set the feature flag back to 0% or 5% immediately", "Fix the config — flag accidentally set to 100% instead of 5%"],
        "hints_medium": ["All prices are $0 — a pricing-related change went too broadly"],
        "hints_hard": [],
    },
    {
        "title": "Session Fixation Vulnerability Detected",
        "description": "Security audit found session fixation vulnerability. Session ID not regenerated after authentication. Attacker could force a known session ID and hijack after login.",
        "service": "session-management",
        "severity": "SEV2",
        "root_cause": "security_breach",
        "correct_team": "security",
        "correct_remediation": "fix_config",
        "symptoms": ["Session ID persists across authentication boundary", "Pre-authentication session token accepted post-login", "Vulnerability exploitable via crafted login links", "Security scanner flagged OWASP A7 — Identification and Authentication Failures"],
        "logs": ["[ALERT] security-scan: Session fixation vulnerability — session not regenerated on login", "[WARN] auth: Session ID 'abc123' used before and after authentication", "[INFO] security: OWASP ZAP scan complete — 1 HIGH severity finding"],
        "metrics": {"vulnerability_severity": "HIGH", "affected_endpoints": 3, "sessions_at_risk": 50000, "cvss_score": 7.5},
        "affected_users": 50000,
        "hints_easy": ["Fix the session config to regenerate session ID after authentication", "Standard fix: call session.invalidate() then create new session on login"],
        "hints_medium": ["Session not regenerated on auth — classic session fixation"],
        "hints_hard": [],
    },
]
